version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: "nginx"
        environment:
            - TZ=America/Sao_Paulo
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        restart: always
        working_dir: /var/www
        volumes:
            - ./../:/var/www
            - ./nginx/ssl:/etc/nginx/ssl
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - /var/log/nginx:/var/log/nginx
            - /etc/hosts:/etc/hosts:ro
    mysql:
        image: mysql
        container_name: "mysql"
        ports:
            - "3306:3306"
        volumes:
            - my-db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: dev
            MYSQL_ROOT_PASSWORD: Hta7827kb
volumes:
    my-db:
